server:
  port: 8080

spring:
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-id: ${spring.application.name}:${server.port}
        catalog-services-watch-enabled: true
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: stock-service
          uri: lb://stock-service
          predicates:
            - Path=/stock/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}
  endpoints:
    web:
      exposure:
        include: health,info,gateway
